sources:
  - name: raw
    database: postgres_db  
    schema: raw  
    tables:
      - name: lis_dates
      - name: json_names
      - name: json_names_nested
      - name: de_holidays
      - name: items

models:
  - name: sel
