sources:
  - name: raw
    database: postgres_db  
    schema: raw  
    tables:
      - name: lis_dates
        columns: 
          - name: dates
            tests:
            - not_null
            - unique
      - name: json_names
      - name: json_names_nested
      - name: de_holidays
      - name: items
        columns:
        - name: item
          tests:
            - col_len:
                testlen: '3'
                severity: warn   # overrides
