name: run dbt debug

on: [push, pull_request,workflow_dispatch]

jobs:
  install-dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: proper directory
        run: cd cv_postgres

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: install dbt postgres
        run: pip install dbt-postgres

      - name: Verify DBT installation
        run: dbt --version

      - name: Run DBT command
        run: dbt debug
